from pydantic import BaseModel, Field

class AgentRequest(BaseModel):
    query: str = Field(..., title="User Query", description="The input string from the user")

class AgentResponse(BaseModel):
    answer: str = Field(..., title="Agent Answer", description="The response generated by the AI agent")
    status: str = Field(default="success")

from typing import Optional, List
from datetime import datetime
from db.models import OpportunityCategory

class OpportunityBase(BaseModel):
    title: str
    description: str
    category: OpportunityCategory
    organization: str
    location: Optional[str] = None
    requirements: Optional[str] = None
    benefits: Optional[str] = None
    application_url: str
    tags: Optional[str] = None
    published_at: datetime
    expires_at: Optional[datetime] = None

class OpportunityResponse(OpportunityBase):
    id: int
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}

class OpportunityListResponse(BaseModel):
    total: int
    items: List[OpportunityResponse]
    skip: int
    limit: int
