from pydantic import BaseModel, Field

class AgentRequest(BaseModel):
    query: str = Field(..., title="User Query", description="The input string from the user")

class AgentResponse(BaseModel):
    answer: str = Field(..., title="Agent Answer", description="The response generated by the AI agent")
    status: str = Field(default="success")
